### ISSUE TITLE
Splash Screen Reload Infiniting

### ISSUE THREAD

**Issue by newerit** [jellyfin-archive/jellyfin-android-original#395]
I am try creating my custom version of android app jellyfin
, but y have this problem reload inifity splashscrean

image = https://ibb.co/RD29N0b

**Comment by thornbill** [comment]
1. This is not the source of the current Jellyfin Android app. That can be found [here](https://github.com/jellyfin/jellyfin-android). 
2. We generally don't provide any support for rebranding our apps.
